Change `make lint` to be comprehensive
I (almost) always run `make lint` on a change I plan on turning into a
pull-request. However, the usefulness of that is limited because it only
performs two Go source code lint checks. Which is a small fraction of the
actual lint checks run in the continuous integration environment. Which
means that I am regularly surprised by CI failures due to lint checks I
didn't think to run because I expected `make lint` to run all the checks
run by the CI environment.

This change modifies the top-level "lint" target to run all the lint checks.
Also, with this change `make lint` produces no output if there is no lint.

diff --git a/tools/pre-push b/tools/pre-push
--- a/tools/pre-push
+++ b/tools/pre-push
@@ -5,21 +5,21 @@
 #   cd .git/hooks # from repo root
 #   ln -s ../../tools/pre-push .
 
-if ! git diff HEAD --quiet; then
-    if git diff --cached --quiet; then
-        echo 'Local changes exist and none is staged; stashing.'
-        git stash
-        trap 'r=$?; git stash pop; trap - EXIT; exit $r' EXIT INT HUP TERM
-    else
-        echo 'Local changes exist and some are staged; not stashing.'
-        echo 'Make a commit, stash all the changes, or unstage all the changes.'
-        exit 1
-	fi
+if ! git diff-index --quiet HEAD; then
+    echo 'Local changes exist.'
+    echo 'Add those changes to the commit(s), stash them, or revert them.'
+    echo
+    git status
+    exit 1
 fi
 
-make test checkstyle lint codespell
-make -C website check-rellinks
-# A quick cross compilation test. Not exhaustive, but will catch most issues.
+# Verify the project is lint free and the tests pass. This simulates what is
+# done in CI and we want to cause the checks to fail with a non-zero status.
+export CI=yes
+make lint
+make test
+
+# A quick cross-compilation test. Not exhaustive, but will catch most issues.
 if test `go env GOOS` = windows; then
     GOOS=linux GOARCH=amd64 go build ./...
 else
